### ISSUE TITLE
WebRTC issue

### ISSUE THREAD

**Issue by csakis** [exo-addons/web-conferencing#11]
I'm using the trial version of exo for evaluating.
When I try to use peer-to-peer video conferencing the webRTC address is always locahost/...., even though the application runs on my home net: 192.168.1.123

**Comment by fdrouet** [comment]
And what is the problem your encounter ?

**Comment by csakis** [comment]
Well, I get an error, since nothing is running on the localhost. The localhost is a client the logged into the server. I'll try to send a picture

**Comment by csakis** [comment]
![2018-09-26](https://user-images.githubusercontent.com/2583367/46127457-efd62980-c1ed-11e8-8cc3-1cdf9f2b23b1.png)

**Comment by fdrouet** [comment]
Please give more details on your eXo Platform installation

- eXo version
- the exact Docker commande line you use to launch it
- the url you use in your browser to access your eXo instance

**Comment by pnedonosko** [comment]
Hi, you must run HTTPS even on localhost.

**Comment by csakis** [comment]
docker run -v exo_trial_data:/srv -p 8080:8080 exoplatform/exo-trial
Exo version is 5.0.3
http://192.168.1.2:8080

Peter is right that WebRTC needs https, without it cannot work. However, in the pop-up video chat window, the address is localhost:8080/webrtc/call/p/....
Shouldn't that be 192.168.1.2/webrtc/call/p/...?

**Comment by csakis** [comment]
Just one more thing:
If I initiate the call from the computer that actually runs the docker image (i.e. localhost), then the video pop-up window works correctly:
![image](https://user-images.githubusercontent.com/2583367/46128706-9a038080-c1f1-11e8-9bda-a67c2595f6d8.png)

**Comment by pnedonosko** [comment]
A call window will use the same host, scheme and port that the Platform page from which it was open. As for HTTPS a call page as such will be loaded but should fail to establish actual RTC connection, it should be failed at browser level API. Isn't a case for you?

**Comment by csakis** [comment]
Peter, look at the two pictures below:
Picture 1. The url shows http://192.168.1.2, I click on the "Call" button:
![image](https://user-images.githubusercontent.com/2583367/46129074-c4097280-c1f2-11e8-9204-d788d4f5c506.png)

Picture 2. The pop up window has *localhost* in it:
![image](https://user-images.githubusercontent.com/2583367/46129124-ec916c80-c1f2-11e8-9a99-e4878727ece1.png)


Thanks for the very quick responses, however, I need to go bed now. Don't expect replies from me for the next 8 hours.

**Comment by fdrouet** [comment]
@csakis please add -e EXO_PROXY_VHOST=192.168.1.2 in your Docker command line to create and launch eXo container. This will configure the underlying Tomcat the good way.

`docker run -v exo_trial_data:/srv -p 8080:8080 -e EXO_PROXY_VHOST=192.168.1.2 exoplatform/exo-trial`

This should solve your 'localhost' url problem.

**Comment by csakis** [comment]
Thanks, Frederic. The proxy settings solved the problem
